spring:
  datasource:
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:21879/railway
    username: postgres
    password: oiBxmVclwsqhXcpqmqQtBEwJvpQLmPXr
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true